Update ChallengePanel Flexbox
kantord/LibreLingo pull request #867
Opened 2020-10-28 14:01 UTC by Sheitak

Hello,

Response to this issue : #841 

I integrated flex-box, however, it is very difficult for me to see the result without launching the application and visualizing things correctly,

thank you for indicating to me the future modification as clearly as possible if necessary, thank you,

2020-10-28 19:48 UTC, kantord commented
> I integrated flex-box, however, it is very difficult for me to see the result without launching the application and visualizing things correctly,

you can launch the application.

you just need to

```
yarn install
yarn web dev
```

as described in the development documentation: https://librelingo.readthedocs.io/en/latest/

Sorry if that was confusing. Do you think the documentation could be improved in some way?

2020-10-28 19:48 UTC, kantord commented
BTW each PR also has it's own stating deployment, see this comment to preview the app with your changes https://github.com/kantord/LibreLingo/pull/867#issuecomment-717953309

2020-10-28 19:49 UTC, kantord commented
![2020-10-28-204903_1021x804_scrot](https://user-images.githubusercontent.com/3704904/97488844-1469d600-195f-11eb-91b4-072fa8e08a80.png)

the layout seems to be broken

2020-10-28 19:51 UTC, kantord requested changes

2020-10-28 19:51 UTC, kantord commented on workspaces/web/src/components/ChallengePanel.svelte
> +  .container {
this is already defined by bulma https://bulma.io/documentation/layout/container/ 

perhaps you could be able to even just reuse something from bulma

2020-11-07 08:19 UTC, kantord commented
Hi @Sheitak how is it going? are you stuck? do you need some help?

2020-11-08 12:24 UTC, Sheitak commented
Hello @kantord , sorry for that response time, I'm busy on other issues right now, struggled because it's not my tech environment, I'm trying to finish this when I have a little time ,

2020-12-09 18:34 UTC, kantord commented
Hi @Sheitak  , how is it going? Do you need some help here?

2021-02-17 07:38 UTC, kantord commented
Feel free to re-open later if you intend to finish it. Feel free to reach out if you need help!

2021-02-17 07:38 UTC, closed without merging